// Generated by CoffeeScript 1.7.1
(function() {
  var tictactoe;

  tictactoe = angular.module('TicTacToe', []);

  tictactoe.controller('BoardController', function($scope) {
    return $scope.cells = {};
  });

  $scope.mark = function(cell) {
    var mark;
    mark = Object.keys($scope.cells).length % 2 === 0 ? 'x' : 'o';
    return $scope.cells[cell] = mark;
  };

}).call(this);

//# sourceMappingURL=application.map
